[package]
name = "cargo-instruments"
version = "0.3.4"
authors = ["Colin Rofls <colin@cmyr.net>"]
license = "MIT"
description = "Generate Xcode Instruments trace files for binary targets."
repository = "https://github.com/cmyr/cargo-instruments"
documentation = "https://github.com/cmyr/cargo-instruments"
categories = ["development-tools::cargo-plugins", "development-tools::profiling"]
keywords = ["profiling", "xcode", "instruments", "macos"]
readme = "README.md"
edition = "2018"

[dependencies]
chrono = "0.4.6"
ctrlc = "3.1.7"
cargo = "0.47.0"
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }
termcolor = "1.0"

[features]
vendored-openssl = ["cargo/vendored-openssl"]
